#!/bin/sh

if [ "$1" == "" ]; then
  echo "Please provide an IP or FQDN"
  exit 1
fi

while true; do
  echo "Trying ${1}:22"
  nc $1 22 < /dev/null
  [ "$?" == "0" ] && break
  echo "sleeping 5..."
  sleep 5
done

ssh $1
