#!/usr/bin/env ruby

#http_proxy = "http://10.44.224.69:3128"

git_bundles = [
  "https://github.com/astashov/vim-ruby-debugger.git",
  "https://github.com/pangloss/vim-javascript.git",
  "https://github.com/tpope/vim-git.git",
  "https://github.com/tpope/vim-haml.git",
  "https://github.com/tpope/vim-markdown.git",
  "https://github.com/tpope/vim-repeat.git",
  "https://github.com/tpope/vim-surround.git",
  "https://github.com/tpope/vim-vividchalk.git",
  "https://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/scrooloose/syntastic",
  "https://github.com/rodjek/vim-puppet.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/JamshedVesuna/vim-markdown-preview.git",
  "https://github.com/fatih/vim-go.git",
]

vim_org_scripts = [
  ["jquery",        "12107", "syntax"],
  ["vim-matchit",   "39", "plugin"],
]
#  ["IndexedSearch", "7062",  "plugin"],

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
if not Dir.exists? "bundle" then
  FileUtils.mkdir(bundles_dir)
end

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

Dir['**/*'].reject {|fn| File.directory?(fn) }.each do |f|
  `dos2unix #{f}`
end
